### ISSUE TITLE
UnnecessaryStringOutput false positive when text starts with # character

### ISSUE THREAD

**Issue by kluka-CS** [sds/haml-lint#344] opened 2021-12-08 06:58 UTC
I am encountering another edge case for the mentioned rule / linter

```haml
%h4= "#{some_value}: #{number_to_currency(some_other_value}"
```

haml-lint then reports
```
UnnecessaryStringOutput: `= "..."` should be rewritten as `...`
```

However when I remove the quotation marks, haml evaluates as a comment (I guess). So then I have no content anymore

**Comment by kwtuku** [comment] 2023-02-27 12:42
I think you need to remove the equals sign `=` as well as the quotation marks `""`.

```haml
%h4 #{some_value}: #{number_to_currency(some_other_value)}
```

**Comment by sds** [comment] 2023-07-15 19:03
Realizing I misread and mislabeled this a long time ago.

Confirming what has already been said: you need to remove the `=` and double quotes. The lint is there to tell you that they aren't necessary. 

Closing as intended behavior.

**Closed by sds** 2023-07-15 19:03 UTC
Labels: question
